In [58]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import LabelEncoder
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split

In [59]:
df1 = pd.read_csv('Data.csv')

In [60]:
df1.head()

,diseases,anxiety and nervousness,depression,shortness of breath,depressive or psychotic symptoms,sharp chest pain,dizziness,insomnia,abnormal involuntary movements,chest tightness,...,stuttering or stammering,problems with orgasm,nose deformity,lump over jaw,sore in nose,hip weakness,back swelling,ankle stiffness or tightness,ankle weakness,neck weakness
0,panic disorder,1,0,1,1,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
1,panic disorder,0,0,1,1,0,1,1,0,0,...,0,0,0,0,0,0,0,0,0,0
2,panic disorder,1,1,1,1,0,1,1,0,0,...,0,0,0,0,0,0,0,0,0,0
3,panic disorder,1,0,0,1,0,1,1,1,0,...,0,0,0,0,0,0,0,0,0,0
4,panic disorder,1,1,0,0,0,0,1,1,1,...,0,0,0,0,0,0,0,0,0,0

In [61]:
df1['diseases'].nunique()

773

In [62]:
df1.shape

(246945, 378)

In [63]:
result = df1['diseases']
result = pd.DataFrame(result)

In [64]:
cols = df1.columns
cols = pd.DataFrame(cols)

In [65]:
le=LabelEncoder()

df1['Disease'] = le.fit_transform(df1['diseases'])

In [66]:
df1.head()

,diseases,anxiety and nervousness,depression,shortness of breath,depressive or psychotic symptoms,sharp chest pain,dizziness,insomnia,abnormal involuntary movements,chest tightness,...,problems with orgasm,nose deformity,lump over jaw,sore in nose,hip weakness,back swelling,ankle stiffness or tightness,ankle weakness,neck weakness,Disease
0,panic disorder,1,0,1,1,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,531
1,panic disorder,0,0,1,1,0,1,1,0,0,...,0,0,0,0,0,0,0,0,0,531
2,panic disorder,1,1,1,1,0,1,1,0,0,...,0,0,0,0,0,0,0,0,0,531
3,panic disorder,1,0,0,1,0,1,1,1,0,...,0,0,0,0,0,0,0,0,0,531
4,panic disorder,1,1,0,0,0,0,1,1,1,...,0,0,0,0,0,0,0,0,0,531

In [67]:
df1 = df1.iloc[:,1:]

In [68]:
df1.head()

,anxiety and nervousness,depression,shortness of breath,depressive or psychotic symptoms,sharp chest pain,dizziness,insomnia,abnormal involuntary movements,chest tightness,palpitations,...,problems with orgasm,nose deformity,lump over jaw,sore in nose,hip weakness,back swelling,ankle stiffness or tightness,ankle weakness,neck weakness,Disease
0,1,0,1,1,0,0,0,0,1,1,...,0,0,0,0,0,0,0,0,0,531
1,0,0,1,1,0,1,1,0,0,1,...,0,0,0,0,0,0,0,0,0,531
2,1,1,1,1,0,1,1,0,0,1,...,0,0,0,0,0,0,0,0,0,531
3,1,0,0,1,0,1,1,1,0,0,...,0,0,0,0,0,0,0,0,0,531
4,1,1,0,0,0,0,1,1,1,0,...,0,0,0,0,0,0,0,0,0,531

In [69]:
X_train,X_test,Y_train,Y_test = train_test_split(df1.iloc[:,0:377],df1.iloc[:,-1],test_size=0.2)

In [70]:
ref = RandomForestClassifier()

In [71]:
# pipe = Pipeline([
#     ('trf1',ref)
# ])

In [72]:
# pipe.fit(X_train,Y_train)

In [73]:
from sklearn.model_selection import cross_val_score
from sklearn.metrics import accuracy_score

In [74]:
# y_pred = pipe.predict(X_test)

In [75]:
# accuracy_score(Y_test,y_pred)

In [76]:
# import pickle
# pickle.dump(pipe,open('pipe.pkl','wb'))

In [77]:
from sklearn.linear_model import LogisticRegression

In [78]:
lr = LogisticRegression()
pipe_lr = Pipeline([
    ('trf1',lr)
])
pipe_lr.fit(X_train,Y_train)
y_pred = pipe_lr.predict(X_test)
accuracy_score(Y_test,y_pred)

0.8665492316102776

In [79]:
import pickle
pickle.dump(pipe_lr,open('pipe_lr.pkl','wb'))

In [80]:
# df2=pd.read_csv('dataset.csv')

In [81]:
# df2.head()

In [82]:
# cdh=df1.columns

In [83]:
# cdh = pd.DataFrame(cdh)

In [84]:
# le=LabelEncoder()

# df1['Disease'] = le.fit_transform(df1['diseases'])

In [85]:
# df1.head()

In [86]:
# df1['diseases'].nunique()

In [87]:
# df1 = df1.iloc[:,1:]

In [88]:
# df1.head()

In [89]:
# X_train,X_test,Y_train,Y_test = train_test_split(df1.iloc[:,0:377],df1.iloc[:,-1],test_size=0.2)

In [90]:
# Y_train

In [91]:
# rf = RandomForestClassifier()

In [92]:
# rf.fit(X_train,Y_train)

In [93]:
# y_pred = rf.predict(X_test)

In [94]:
# from sklearn.metrics import accuracy_score
# accuracy_score(Y_test, y_pred)

In [95]:
# med = pd.read_csv('Medicine.csv')

In [96]:
# med.head()

In [97]:
# med.shape

In [98]:
# (med['condition'] == 'Depression').sum()

In [99]:
# medd = pd.read_csv('medicine_dataset.csv')

In [100]:
# medd.head()

In [101]:
# medd.shape